export const OPEN_MODAL_PRODUCT_PROCESS = "OPEN_MODAL_PRODUCT_PROCESS";
export const CLOSE_MODAL_PRODUCT_PROCESS = "CLOSE_MODAL_PRODUCT_PROCESS";
export const OPEN_MODAL_PRODUCT_NG = "OPEN_MODAL_PRODUCT_NG";
export const CLOSE_MODAL_PRODUCT_NG = "CLOSE_MODAL_PRODUCT_NG";

export const JUMP_WAREHOUSE_IMPORT = "JUMP_WAREHOUSE_IMPORT";
export const JUMP_WAREHOUSE_CREATE = "JUMP_WAREHOUSE_CREATE";
export const JUMP_SALE_ORDER_REGISTER = "JUMP_SALE_ORDER_REGISTER";

export const CLEAR_WAREHOUSE_IMPORT = "CLEAR_WAREHOUSE_IMPORT";
export const CLEAR_WAREHOUSE_CREATE = "CLEAR_WAREHOUSE_CREATE";

export const JUMP_PRODUCTION_ORDER_REGISTER = "JUMP_PRODUCTION_ORDER_REGISTER";
export const JUMP_PURCHASE_ORDER_REGISTER = "JUMP_PURCHASE_ORDER_REGISTER";
export const JUMP_PURCHASE_REQUISITION = "JUMP_PURCHASE_REQUISITION";
