export const OPEN_MODAL_PRODUCT_ITEM = "OPEN_MODAL_PRODUCT_ITEM";
export const CLOSE_MODAL_PRODUCT_ITEM = "CLOSE_MODAL_PRODUCT_ITEM";
export const OPEN_MODAL_PRODUCT_PROCESS = "OPEN_MODAL_PRODUCT_PROCESS";
export const CLOSE_MODAL_PRODUCT_PROCESS = "CLOSE_MODAL_PRODUCT_PROCESS";
export const OPEN_MODAL_PRODUCT_NG = "OPEN_MODAL_PRODUCT_NG";
export const CLOSE_MODAL_PRODUCT_NG = "CLOSE_MODAL_PRODUCT_NG";
